### ISSUE TITLE
Difference in behaviour with destinationPortRange vs destinationPortRanges

### ISSUE THREAD

**Issue by alexjh** [colstrom/cloudstrap-azure#4]
Follow up to my previous issue, maybe it wasn't the comma separated list?

`"name": "Port_2793"` is my manually created one through the web UI that works, the one with the cloudstrap generated name doesn't work. The only difference I see is the destinationPortRange vs destinationPortRange*s*.

```
alexh@linux-2iaq:~/sandbox/azure> az network nsg rule show --nsg-name k8s-master-A0C0BDE5-nsg --resource-group cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46 --name Port_2793
{
  "access": "Allow",
  "description": null,
  "destinationAddressPrefix": "*",
  "destinationAddressPrefixes": [],
  "destinationApplicationSecurityGroups": null,
  "destinationPortRange": "2793",
  "destinationPortRanges": [],
  "direction": "Inbound",
  "etag": "W/\"319c5721-c2cc-4154-b84d-8cefac778ae0\"",
  "id": "/subscriptions/f416ccc9-4483-4708-b2d8-e36230df6f2d/resourceGroups/cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46/providers/Microsoft.Network/networkSecurityGroups/k8s-master-A0C0BDE5-nsg/securityRules/Port_2793",
  "name": "Port_2793",
  "priority": 116,
  "protocol": "TCP",
  "provisioningState": "Succeeded",
  "resourceGroup": "cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46",
  "sourceAddressPrefix": "*",
  "sourceAddressPrefixes": [],
  "sourceApplicationSecurityGroups": null,
  "sourcePortRange": "*",
  "sourcePortRanges": []
}
alexh@linux-2iaq:~/sandbox/azure> az network nsg rule show --nsg-name k8s-master-A0C0BDE5-nsg --resource-group cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46 --name cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46-2793
{
  "access": "Allow",
  "description": null,
  "destinationAddressPrefix": "*",
  "destinationAddressPrefixes": [],
  "destinationApplicationSecurityGroups": null,
  "destinationPortRange": null,
  "destinationPortRanges": [
    "2793"
  ],
  "direction": "Inbound",
  "etag": "W/\"319c5721-c2cc-4154-b84d-8cefac778ae0\"",
  "id": "/subscriptions/f416ccc9-4483-4708-b2d8-e36230df6f2d/resourceGroups/cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46/providers/Microsoft.Network/networkSecurityGroups/k8s-master-A0C0BDE5-nsg/securityRules/cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46-2793",
  "name": "cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46-2793",
  "priority": 106,
  "protocol": "Tcp",
  "provisioningState": "Succeeded",
  "resourceGroup": "cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46",
  "sourceAddressPrefix": "*",
  "sourceAddressPrefixes": [],
  "sourceApplicationSecurityGroups": null,
  "sourcePortRange": "*",
  "sourcePortRanges": []
}
```

The error message is very confusing because it looks like that's what cloudstrap is actually doing:

```
Error creating load balancer (will retry): Failed to create load balancer for service uaa/uaa-public: network.SecurityGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="SecurityRuleParametersMissingForPortRanges" Message="Required security rule parameters are missing for security rule with Id: /subscriptions/f416ccc9-4483-4708-b2d8-e36230df6f2d/resourceGroups/cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46/providers/Microsoft.Network/networkSecurityGroups/k8s-master-A0C0BDE5-nsg/securityRules/cloudstrap.7e7ddcb0-40e3-0136-bc86-0cdcd44b8f46-2793. Security rule must specify either DestinationPortRange or DestinationPortRanges." Details=[]
```

**Comment by colstrom** [comment]
This is fixed in `0.7.0.pre`, by creating individual rules for each port.

Thanks for highlighting this!

**Comment by alexjh** [comment]
It still wasn't fixed because it was *slightly* different to what kube was expecting. I made a PR that should fix it.
